### ISSUE TITLE
cannot load such file -- refinery/core/nil_user

### ISSUE THREAD

**Issue by ttmthanh** [refinery/refinerycms-search#72]
I'm trying to install gem 'refinerycms-search' for the project. But when running 'rails generate refinery: search' the error is as shown. Please tell me the reason.
`rails generate refinery:search
/home/thanh/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- refinery/core/nil_user (LoadError)
	from /home/thanh/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/thanh/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/thanh/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /home/thanh/monnhatban/config/initializers/refinery/core/authorisation_adapter.rb:1:in `<top (required)>'
	from /home/thanh/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
	from /home/thanh/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
	from /home/thanh/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/thanh/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
	from /home/thanh/.rvm/gems/ruby-2.3.4/gems/railties-4.2.0/lib/rails/engine.rb:652:in `block in load_config_initializer'
	from /home/thanh/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.0/lib/active_support/notifications.rb:166:in `instrument'
	from /home/thanh/.rvm/gems/ruby-2.3.4/gems/railties-4.2.0/lib/rails/engine.rb:651:in `load_config_initializer'
	from /home/thanh/.rvm/gems/ruby-2.3.4/gems/railties-4.2.0/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
	from /home/thanh/.rvm/gems/ruby-2.3.4/gems/railties-4.2.0/lib/rails/engine.rb:615:in `each'
	from /home/thanh/.rvm/gems/ruby-2.3.4/gems/railties-4.2.0/lib/rails/engine.rb:615:in `block in <class:Engine>'
	from /home/thanh/.rvm/gems/ruby-2.3.4/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/thanh/.rvm/gems/ruby-2.3.4/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
	from /home/thanh/.rvm/gems/ruby-2.3.4/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/thanh/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /home/thanh/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /home/thanh/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /home/thanh/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /home/thanh/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /home/thanh/.rvm/gems/ruby-2.3.4/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `each'
	from /home/thanh/.rvm/gems/ruby-2.3.4/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /home/thanh/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:415:in `call'
	from /home/thanh/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /home/thanh/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /home/thanh/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /home/thanh/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /home/thanh/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /home/thanh/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /home/thanh/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /home/thanh/.rvm/gems/ruby-2.3.4/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/thanh/.rvm/gems/ruby-2.3.4/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
	from /home/thanh/.rvm/gems/ruby-2.3.4/gems/railties-4.2.0/lib/rails/railtie.rb:194:in `public_send'
	from /home/thanh/.rvm/gems/ruby-2.3.4/gems/railties-4.2.0/lib/rails/railtie.rb:194:in `method_missing'
	from /home/thanh/monnhatban/config/environment.rb:5:in `<top (required)>'
	from /home/thanh/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /home/thanh/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/thanh/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/thanh/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /home/thanh/.rvm/gems/ruby-2.3.4/gems/railties-4.2.0/lib/rails/application.rb:328:in `require_environment!'
	from /home/thanh/.rvm/gems/ruby-2.3.4/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:142:in `require_application_and_environment!'
	from /home/thanh/.rvm/gems/ruby-2.3.4/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:128:in `generate_or_destroy'
	from /home/thanh/.rvm/gems/ruby-2.3.4/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:50:in `generate'
	from /home/thanh/.rvm/gems/ruby-2.3.4/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/thanh/.rvm/gems/ruby-2.3.4/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
`

**Comment by ttmthanh** [comment]
Here is my gemfile


> # vim: filetype=ruby
source 'https://rubygems.org'
ruby '2.3.4'

gem 'rails', '4.2.0'
gem 'slim'
gem 'jquery-rails'
gem 'turbolinks'
gem 'metamagic'
gem 'unicorn'
gem 'rmagick'
gem 'whenever'
gem 'lazyload-rails'

gem 'yaml_db'
gem 'jpmobile'

gem 'jbuilder'

gem 'sdoc', '~> 0.4.1', group: :doc
# Refinery CMS
# gem 'refinerycms', '2.1.5'
gem 'thin'

gem 'refinerycms', github: 'refinery/refinerycms', branch: 'master'
# Optionally, specify additional Refinery CMS Extensions here:
gem 'refinerycms-acts-as-indexed', '~> 3.0.0'
gem 'refinerycms-inquiries', github: 'refinery/refinerycms-inquiries', branch: 'master'
gem 'refinerycms-search', github: 'refinery/refinerycms-search', branch: '3-0-stable'
# gem 'refinerycms-search', github: 'refinery/refinerycms-search', branch: '3-0-stable'
gem 'refinerycms-page-images', github: 'refinery/refinerycms-page-images', branch: "master"
gem 'refinerycms-i18n', github: 'refinery/refinerycms-i18n', branch: 'master'
gem 'refinerycms-wymeditor', ['~> 1.0', '>= 1.0.6']
gem 'refinerycms-authentication-devise', '~> 1.0.4'
gem 'zilch-authorisation', '~> 0.0.1'

gem 'therubyracer'
gem "font-awesome-rails"
gem "exception_notification"

group :development, :test do
  gem 'quiet_assets'
  gem 'sqlite3'
  gem 'byebug'
  gem 'web-console'
  gem 'spring'
end

group :development do
  gem 'pry-rails'
end

# Gems used only for assets and not required
# in production environments by default.
gem 'sass-rails'
gem 'coffee-rails'
gem 'uglifier'
gem 'bootstrap-sass'

group :production do
  gem 'fog'
  gem 'rails_12factor'
  gem 'pg'
  gem "dragonfly-s3_data_store", "1.3.0"
end

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
